[build]
  base = "packages/web"
  publish = "packages/web/dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://sem37-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "https://auth-3778.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
