[build]
  base = "packages/web"
  command = "npm install --production=false && npm run build"
  publish = "dist"
  
[build.environment]
  # Set Tailwind in build mode
  TAILWIND_MODE = "build"
  # Force relative API paths
  VITE_ALLOW_PROD_RELATIVE = "1"

# Handle API proxying to avoid CORS issues
[[redirects]]
  from = "/api/*"
  to = "https://sem37-api.onrender.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Proxy-Request = "true"

# Auth service proxying
[[redirects]]
  from = "/auth/*"
  to = "https://auth-3778.onrender.com/:splat"
  status = 200
  force = true

# SPA fallback - must be the last redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Cache assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable Lighthouse plugin for performance insights
[[plugins]]
  package = "@netlify/plugin-lighthouse"
