[build]
  base = "packages/web"
  command = "npm install --legacy-peer-deps --include=dev && npm run build"
  publish = "dist"

# Ensure dev dependencies are installed
[build.environment]
  TAILWIND_MODE = "build"
  NODE_ENV = "development"

[[redirects]]
  from = "/api/*"
  to = "https://sem37-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "https://auth-3778.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
